/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.info.Info;
import org.example.json.Json;
import picocli.CommandLine;
import picocli.CommandLine.Option;

class Netcdf implements Runnable {

    @Option(names = {"-v", "--version"})
    private boolean showVersion;

    @Override
    public void run() {
        if (showVersion) {
            System.out.println("0.0.1");
        }
    }

    public static void main(String[] args) {

        CommandLine commandLine = new CommandLine(new Netcdf())
                .addSubcommand(new CommandLine.HelpCommand())
                .addSubcommand(new Json())
                .addSubcommand(new Info());

        System.exit(commandLine.execute(args));
    }
}
