[versions]
picocli = "4.7.6"
netcdf = "5.5.3"
guava = "32.1.3-jre"
jackson = "2.11.1"
junit-jupiter = "5.10.1"

[libraries]
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
picocli-gen = { module = "info.picocli:picocli-codegen", version.ref = "picocli" }

netcdf = { module = "io.github.stellarsunset:netcdf", version = "0.0.2" }
# Runtime dependencies supporting specific file formats
bufr = { module = "edu.ucar:bufr", version.ref = "netcdf" }
grib = { module = "edu.ucar:grib", version.ref = "netcdf" }
opendap = { module = "edu.ucar:opendap", version.ref = "netcdf" }
zarr = { module = "edu.ucar:cdm-zarr", version.ref = "netcdf" }

jackson = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }

guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }

[bundles]
picocli = ["picocli", "picocli-gen"]