/*
 * This source file was generated by the Gradle 'init' task
 */
package com.stellarsunset.netcdf.cli;


import com.stellarsunset.netcdf.cli.describe.Describe;
import com.stellarsunset.netcdf.cli.json.Json;
import picocli.CommandLine;
import picocli.CommandLine.Option;

import java.util.concurrent.Callable;

class Netcdf implements Callable<Integer> {

    @Option(names = {"-v", "--version"})
    private boolean version = false;

    @Override
    public Integer call() {
        if (version) {
            System.out.print("0.0.1");
        }
        return 0;
    }

    public static void main(String[] args) {

        CommandLine commandLine = new CommandLine(new Netcdf())
                .addSubcommand(new CommandLine.HelpCommand())
                .addSubcommand(new Json())
                .addSubcommand(new Describe());

        System.exit(commandLine.execute(args));
    }
}
