/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class NetcdfTest {
    @Test void appHasAGreeting() {
        Netcdf classUnderTest = new Netcdf();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
